docker compose \
    -f docker-compose.airflow.yml \
    -f docker-compose.inference.yml \
    -f docker-compose.kafka.yml \
    -f docker-compose.metric.yml \
    -f docker-compose.pipeline.yml \
    -f docker-compose.spark-control-plane.yml \
    -f docker-compose.storage.yml \
    -f docker-compose.thrift.yml \
    up -d --force-recreate