CREATE USER iceberg WITH ENCRYPTED PASSWORD 'iceberg';
CREATE DATABASE iceberg;
ALTER DATABASE iceberg OWNER TO iceberg;

CREATE USER superset WITH ENCRYPTED PASSWORD 'superset';
CREATE DATABASE superset;
GRANT ALL PRIVILEGES ON DATABASE superset TO superset;
-- ALTER DATABASE superset OWNER TO superset;