FROM ghcr.io/jmhwang-dev/spark-minio-base:4.0.0

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    jupyterlab \
    pandas \
    matplotlib \
    ipykernel

WORKDIR /opt/spark/work-dir

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]

USER spark