FROM apache/spark:4.0.0

# 필요한 Hadoop AWS JAR 및 AWS SDK 추가
RUN curl -o /opt/spark/jars/hadoop-aws-3.4.1.jar \
      https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.4.1/hadoop-aws-3.4.1.jar && \
    curl -o /opt/spark/jars/aws-java-sdk-bundle-1.12.783.jar \
      https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.783/aws-java-sdk-bundle-1.12.783.jar
