from service.init.kafka import *

class Common():
    BUCKET = "warehouse_dev"

class Bronze(Common):
    NAMESPACE = 'bronze'
    
    ORDER_ITEM_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.ORDER_ITEM}'
    PRODUCT_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.PRODUCT}'
    CUSTOMER_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.CUSTOMER}'
    SELLER_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.SELLER}'
    GEOLOCATION_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.GEOLOCATION}'
    ORDER_STATUS_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.ORDER_STATUS}'
    PAYMENT_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.PAYMENT}'
    ESTIMATED_DELIVERY_DATE_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.ESTIMATED_DELIVERY_DATE}'
    REVIEW_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.REVIEW}'

class Silver(Common):
    NAMESPACE = 'silver'

    ORDER_ITEM_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.ORDER_ITEM}'
    PRODUCT_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.PRODUCT}'
    CUSTOMER_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.CUSTOMER}'
    SELLER_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.SELLER}'
    GEOLOCATION_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.GEOLOCATION}'
    ORDER_STATUS_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.ORDER_STATUS}'
    PAYMENT_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.PAYMENT}'
    ESTIMATED_DELIVERY_DATE_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.ESTIMATED_DELIVERY_DATE}'
    REVIEW_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.REVIEW}'

    INFERENCE_REVIEW_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.INFERENCED_REVIEW}'
    PREPROCESSED_REVIEW_TABLE_IDENTIFIER = f'{Common.BUCKET}.{NAMESPACE}.{Topic.PREPROCESSED_REVIEW}'