name: 'warehouse_dev'
version: '1.0.0'
config-version: 2

profile: 'warehouse_dev'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  warehouse_dev:
    +materialized: table
    +file_format: iceberg
    staging:
      +materialized: view
    marts:
      +materialized: table
      +file_format: iceberg